//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DpStatConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableDates_BASE_view
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> AgreedDate { get; set; }
        public string BranchNo { get; set; }
        public string ADASType { get; set; }
        public string ADASTypeDescription { get; set; }
        public string WorkType { get; set; }
        public string WorkTypeLHSDescription { get; set; }
        public string WorkTypeRHSDescription { get; set; }
        public string Branch_Name { get; set; }
        public string Member_Number { get; set; }
        public string Member_Description { get; set; }
        public string Member_Short_Name { get; set; }
        public string BNNo { get; set; }
        public Nullable<int> BNStyle { get; set; }
        public string BNName { get; set; }
        public string BNNo_Style_Description { get; set; }
        public string Location_Type_Description { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string AreaName { get; set; }
        public string ISORegion { get; set; }
        public string LocationType { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public Nullable<int> Working_Days { get; set; }
    }
}
