//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DpStatConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableAppointmentDate
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> AggreedDate { get; set; }
        public string BranchNo { get; set; }
        public string BNStyle { get; set; }
        public string LocationType { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
    }
}
