//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DpStatConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationTypeParam
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string LocationType { get; set; }
    }
}
